using DomainApiNET.Misc;

namespace DomainApiNET.Enums
{
    public enum TLD
    {
        [StringValue("org.lv")]
        org_lv,
        [StringValue("net.lv")]
        net_lv,
        [StringValue("coop")]
        coop,
        [StringValue("asia")]
        asia,
        [StringValue("at")]
        at,
        [StringValue("be")]
        be,
        [StringValue("nl")]
        nl,
        [StringValue("de")]
        de,
        [StringValue("gr")]
        gr,
        [StringValue("it")]
        it,
        [StringValue("fi")]
        fi,
        [StringValue("ru")]
        ru,
        [StringValue("ch")]
        ch,
        [StringValue("li")]
        li,
        [StringValue("co.at")]
        co_at,
        [StringValue("ro")]
        ro,
        [StringValue("lv")]
        lv,
        [StringValue("hu")]
        hu,
        [StringValue("sk")]
        sk,
        [StringValue("or.at")]
        or_at,
        [StringValue("no")]
        no,
        [StringValue("com.gr")]
        com_gr,
        [StringValue("by")]
        by,
        [StringValue("com.tr")]
        com_tr,
        [StringValue("com.gi")]
        com_gi,
        [StringValue("ua")]
        ua,
        [StringValue("com.ua")]
        com_ua,
        [StringValue("fo")]
        fo,
        [StringValue("je")]
        je,
        [StringValue("si")]
        si,
        [StringValue("co.hu")]
        co_hu,
        [StringValue("com.lv")]
        com_lv,
        [StringValue("com.hr")]
        com_hr,
        [StringValue("hr")]
        hr,
        [StringValue("bg")]
        bg,
        [StringValue("rs")]
        rs,
        [StringValue("co.rs")]
        co_rs,
        [StringValue("web.tr")]
        web_tr,
        [StringValue("gen.tr")]
        gen_tr,
        [StringValue("com.mt")]
        com_mt,
        [StringValue("is")]
        is_,
        [StringValue("gg")]
        gg,
        [StringValue("ba")]
        ba,
        [StringValue("com.ru")]
        com_ru,
        [StringValue("com")]
        com,
        [StringValue("net")]
        net,
        [StringValue("asia.com")]
        asia_com,
        [StringValue("dk")]
        dk,
        [StringValue("fr")]
        fr,
        [StringValue("info")]
        info,
        [StringValue("org")]
        org,
        [StringValue("name")]
        name,
        [StringValue("lu")]
        lu,
        [StringValue("gr.com")]
        gr_com,
        [StringValue("re")]
        re,
        [StringValue("uk.net")]
        uk_net,
        [StringValue("se")]
        se,
        [StringValue("ee")]
        ee,
        [StringValue("yt")]
        yt,
        [StringValue("me")]
        me,
        [StringValue("lt")]
        lt,
        [StringValue("tel")]
        tel,
        [StringValue("no.com")]
        no_com,
        [StringValue("pro")]
        pro,
        [StringValue("xxx")]
        xxx,
        [StringValue("mobi")]
        mobi,
        [StringValue("jobs")]
        jobs,
        [StringValue("co.nl")]
        co_nl,
        [StringValue("wf")]
        wf,
        [StringValue("se.net")]
        se_net,
        [StringValue("eu")]
        eu,
        [StringValue("biz")]
        biz,
        [StringValue("co.ee")]
        co_ee,
        [StringValue("tf")]
        tf,
        [StringValue("cz")]
        cz,
        [StringValue("im")]
        im,
        [StringValue("ie")]
        ie,
        [StringValue("pm")]
        pm,
        [StringValue("gb.com")]
        gb_com,
        [StringValue("aero")]
        aero,
        [StringValue("su")]
        su,
        [StringValue("co.im")]
        co_im,
        [StringValue("co.no")]
        co_no,
        [StringValue("com.es")]
        com_es,
        [StringValue("es")]
        es,
        [StringValue("nom.es")]
        nom_es,
        [StringValue("org.es")]
        org_es,
        [StringValue("info.pl")]
        info_pl,
        [StringValue("pl")]
        pl,
        [StringValue("net.pl")]
        net_pl,
        [StringValue("biz.pl")]
        biz_pl,
        [StringValue("org.pl")]
        org_pl,
        [StringValue("com.pl")]
        com_pl,
        [StringValue("com.de")]
        com_de,
        [StringValue("ru.com")]
        ru_com,
        [StringValue("org.uk")]
        org_uk,
        [StringValue("uk.com")]
        uk_com,
        [StringValue("se.com")]
        se_com,
        [StringValue("eu.com")]
        eu_com,
        [StringValue("co.uk")]
        co_uk,
        [StringValue("de.com")]
        de_com,
        [StringValue("pt")]
        pt,
        [StringValue("gb.net")]
        gb_net,
        [StringValue("com.pt")]
        com_pt,
        [StringValue("hu.com")]
        hu_com,
        [StringValue("com.ro")]
        com_ro
    }
}